export const DOCTOR_LOGIN_REQUEST = "DOCTOR_LOGIN_REQUEST"
export const DOCTOR_LOGIN_SUCCESS = "DOCTOR_LOGIN_SUCCESS"
export const DOCTOR_LOGIN_FAIL = "DOCTOR_LOGIN_FAIL"
export const DOCTOR_LOGOUT = "DOCTOR_LOGOUT"

export const DOCTOR_REGISTER_REQUEST = "DOCTOR_REGISTER_REQUEST";
export const DOCTOR_REGISTER_FAIL = "DOCTOR_REGISTER_FAIL";
export const DOCTOR_REGISTER_SUCCESS = "DOCTOR_REGISTER_SUCCESS";

export const DOCTOR_UPDATE_PROFILE = "DOCTOR_UPDATE_PROFILE"