export const HOSPITAL_LOGIN_REQUEST= "HOSPITAL_LOGIN_REQUEST"
export const HOSPITAL_LOGIN_SUCCESS= "HOSPITAL_LOGIN_SUCCESS"
export const HOSPITAL_LOGIN_FAIL= "HOSPITAL_LOGIN_FAIL"
export const HOSPITAL_LOGOUT= "HOSPITAL_LOGOUT"

export const HOSPITAL_REGISTER_REQUEST = "HOSPITAL_REGISTER_REQUEST";
export const HOSPITAL_REGISTER_FAIL = "HOSPITAL_REGISTER_FAIL";
export const HOSPITAL_REGISTER_SUCCESS = "HOSPITAL_REGISTER_SUCCESS";


export const HOSPITAL_PROFILE_EDIT = "HOSPITAL_PROFILE_EDIT"
export const HOSPITAL_EVENTS_ADD = "HOSPITAL_EVENTS_ADD"